"""write_rca_tests.py - Helper to write rca/rca_tests.py"""
import pathlib

DEST = pathlib.Path(__file__).parent / "rca" / "rca_tests.py"

LINES = [
    '"""rca/rca_tests.py',
    "",
    "Unit and integration tests for RCA V1.",
    "",
    "Run with:",
    "    python -m pytest rca/rca_tests.py -v",
    "",
    "Coverage:",
    "- SyntaxAnalyzer (F1): traceback resolution, <string> fallback, confidence",
    "- DependencyAnalyzer (F2): missing, invalid requirement, build failure",
    "- TestFailureAnalyzer (F3): pytest evidence, Python exceptions inside tests",
    "- TimeoutAnalyzer (F4): full/partial evidence, no unverified-cause assertions",
    "- FallbackAnalyzer: runtime_error, empty log, unknown",
    "- RCAEngine: dispatcher order, safety fallback, batch analysis",
    '"""',
    "",
    "from __future__ import annotations",
    "import pytest",
    "from rca.schema import (",
    "    RCAReport,",
    "    CAUSAL_CODE_DEFECT, CAUSAL_DEPENDENCY,",
    "    CAUSAL_TEST, CAUSAL_TIMEOUT, CAUSAL_UNKNOWN,",
    ")",
    "from rca.engine import RCAEngine, get_default_engine, analyze_record",
    "from rca.analyzers.syntax import SyntaxAnalyzer",
    "from rca.analyzers.dependency import DependencyAnalyzer",
    "from rca.analyzers.test_failure import TestFailureAnalyzer",
    "from rca.analyzers.timeout import TimeoutAnalyzer",
    "from rca.analyzers.fallback import FallbackAnalyzer",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# Record factories",
    "# ---------------------------------------------------------------------------",
    "",
    "def _f1(*, error_type='SyntaxError', error_message='invalid syntax',",
    "         file_path='/workspace/app.py', line_number=42,",
    "         traceback_lines=None, run_id='f1_test_001'):",
    "    return {",
    "        'run_id': run_id, 'timestamp': '2026-01-01T00:00:00Z',",
    "        'failure_class': 'syntax_error', 'failure_subcategory': error_type,",
    "        'error_type': error_type, 'error_message': error_message,",
    "        'file_path': file_path, 'line_number': line_number,",
    "        'traceback_lines': traceback_lines or [], 'failed_step': 'Check App Syntax',",
    "        'execution_path': ['Checkout', 'Check App Syntax'], 'stage': 'build',",
    "        'exit_code': 1, 'evidence_lines': [], 'log_text': '...',",
    "    }",
    "",
    "",
    "def _f2(*, failure_subcategory='pip_missing_dependency',",
    "         failing_package='nonexistent-pkg==9.9.9', python_version='3.11.4',",
    "         run_id='f2_test_001', pip_commands=None):",
    "    return {",
    "        'run_id': run_id, 'timestamp': '2026-01-01T00:00:00Z',",
    "        'failure_class': 'dependency_error', 'failure_subcategory': failure_subcategory,",
    "        'failing_package': failing_package, 'python_version': python_version,",
    "        'pip_commands': pip_commands or ['pip install -r requirements.txt'],",
    "        'failed_step': 'Install Dependencies',",
    "        'execution_path': ['Checkout', 'Set Up Python', 'Install Dependencies'],",
    "        'stage': 'build', 'exit_code': 1,",
    "        'evidence_lines': ['ERROR: Could not find a version that satisfies the requirement nonexistent-pkg==9.9.9'],",
    "        'log_text': '...',",
    "    }",
    "",
    "",
    "def _f3(*, test_error_type='AssertionError', error_message='assert 0 == 1',",
    "         failed_test_ids=None, tests_failed=3, tests_passed=17,",
    "         tests_collected=20, traceback_lines=None, run_id='f3_test_001'):",
    "    return {",
    "        'run_id': run_id, 'timestamp': '2026-01-01T00:00:00Z',",
    "        'failure_class': 'test_failure', 'failure_subcategory': test_error_type,",
    "        'test_error_type': test_error_type, 'error_message': error_message,",
    "        'failed_test_ids': failed_test_ids or ['tests/test_core.py::test_add'],",
    "        'tests_failed': tests_failed, 'tests_passed': tests_passed,",
    "        'tests_collected': tests_collected, 'traceback_lines': traceback_lines or [],",
    "        'failed_step': 'Run Tests',",
    "        'execution_path': ['Checkout', 'Set Up Python', 'Install Dependencies', 'Run Tests'],",
    "        'stage': 'test', 'exit_code': 1, 'evidence_lines': [], 'log_text': '...',",
    "    }",
    "",
    "",
    "def _f4(*, timeout_duration_min=6.0, elapsed_step_seconds=None,",
    "         orphan_process='python /home/runner/work/repo/run_tests.py',",
    "         failed_step='Run Tests', run_id='f4_test_001'):",
    "    return {",
    "        'run_id': run_id, 'timestamp': '2026-01-01T00:00:00Z',",
    "        'failure_class': 'timeout', 'failure_subcategory': 'gha_timeout',",
    "        'timeout_duration_min': timeout_duration_min,",
    "        'elapsed_step_seconds': elapsed_step_seconds,",
    "        'orphan_process': orphan_process, 'failed_step': failed_step,",
    "        'execution_path': ['Checkout', 'Set Up Python', 'Install Dependencies', 'Run Tests'],",
    "        'stage': 'test', 'exit_code': 1,",
    "        'evidence_lines': [",
    "            \"##[error]The action 'Run Tests' has timed out after 6 minutes\",",
    "            'Terminate orphan process: pid (1234) (python /home/runner/work/repo/run_tests.py)',",
    "        ],",
    "        'log_text': '...',",
    "    }",
    "",
    "",
    "# ===========================================================================",
    "# SyntaxAnalyzer",
    "# ===========================================================================",
    "",
    "class TestSyntaxAnalyzer:",
    "    def setup_method(self):",
    "        self.a = SyntaxAnalyzer()",
    "",
    "    def test_can_analyze_syntax_error_class(self):",
    "        assert self.a.can_analyze(_f1()) is True",
    "",
    "    def test_can_analyze_indentation_error_type(self):",
    "        assert self.a.can_analyze({'failure_class': 'runtime_error', 'error_type': 'IndentationError'}) is True",
    "",
    "    def test_can_analyze_tab_error_type(self):",
    "        assert self.a.can_analyze({'failure_class': 'unknown', 'error_type': 'TabError'}) is True",
    "",
    "    def test_cannot_analyze_dependency_error(self):",
    "        assert self.a.can_analyze(_f2()) is False",
    "",
    "    def test_returns_rca_report(self):",
    "        assert isinstance(self.a.analyze(_f1()), RCAReport)",
    "",
    "    def test_causal_category(self):",
    "        assert self.a.analyze(_f1()).causal_category == CAUSAL_CODE_DEFECT",
    "",
    "    def test_failure_class_preserved(self):",
    "        assert self.a.analyze(_f1()).failure_class == 'syntax_error'",
    "",
    "    def test_subcategory_is_error_type(self):",
    "        assert self.a.analyze(_f1(error_type='IndentationError')).failure_subcategory == 'IndentationError'",
    "",
    "    def test_run_id_propagated(self):",
    "        assert self.a.analyze(_f1(run_id='abc-123')).run_id == 'abc-123'",
    "",
    "    def test_high_confidence_with_full_details(self):",
    "        assert self.a.analyze(_f1()).rca_confidence == 1.0",
    "",
    "    def test_medium_confidence_without_file(self):",
    "        assert self.a.analyze(_f1(file_path=None, line_number=None)).rca_confidence == 0.8",
    "",
    "    def test_string_path_triggers_traceback_resolution(self):",
    "        tb = [",
    "            'File \"<string>\", line 1, in <module>',",
    "            'File \"/workspace/app.py\", line 42',",
    "            'SyntaxError: invalid syntax',",
    "        ]",
    "        r = self.a.analyze(_f1(file_path='<string>', line_number=None, traceback_lines=tb))",
    "        assert r.observed_evidence['source_file'] == '/workspace/app.py'",
    "        assert r.observed_evidence['source_line'] == 42",
    "",
    "    def test_traceback_resolution_evidence_source(self):",
    "        tb = [",
    "            'File \"<string>\", line 1, in <module>',",
    "            'File \"/workspace/app.py\", line 7',",
    "        ]",
    "        r = self.a.analyze(_f1(file_path='<string>', line_number=None, traceback_lines=tb))",
    "        assert r.evidence_sources['source_file'] == 'parser.traceback_lines'",
    "",
    "    def test_no_tb_medium_confidence(self):",
    "        r = self.a.analyze(_f1(file_path='<string>', line_number=None, traceback_lines=[]))",
    "        assert r.rca_confidence == 0.8",
    "",
    "    def test_summary_contains_error_type(self):",
    "        assert 'SyntaxError' in self.a.analyze(_f1()).summary",
    "",
    "    def test_summary_contains_file_path(self):",
    "        assert '/workspace/app.py' in self.a.analyze(_f1()).summary",
    "",
    "    def test_summary_contains_line_number(self):",
    "        assert '42' in self.a.analyze(_f1()).summary",
    "",
    "    def test_local_cmd_uses_file(self):",
    "        assert '/workspace/app.py' in self.a.analyze(_f1()).local_reproduction_command",
    "",
    "    def test_local_cmd_none_without_file(self):",
    "        r = self.a.analyze(_f1(file_path='<string>', traceback_lines=[]))",
    "        assert r.local_reproduction_command is None",
    "",
    "    def test_investigation_populated(self):",
    "        assert len(self.a.analyze(_f1()).suggested_investigation) >= 2",
    "",
    "    def test_limitations_populated(self):",
    "        assert len(self.a.analyze(_f1()).limitations) >= 1",
    "",
    "    def test_to_dict_serializable(self):",
    "        d = self.a.analyze(_f1()).to_dict()",
    "        assert 'failure_class' in d and 'rca_confidence' in d",
    "",
    "    def test_to_json_serializable(self):",
    "        import json",
    "        parsed = json.loads(self.a.analyze(_f1()).to_json())",
    "        assert parsed['failure_class'] == 'syntax_error'",
    "",
    "",
    "# ===========================================================================",
    "# DependencyAnalyzer",
    "# ===========================================================================",
    "",
    "class TestDependencyAnalyzer:",
    "    def setup_method(self):",
    "        self.a = DependencyAnalyzer()",
    "",
    "    def test_can_analyze(self):",
    "        assert self.a.can_analyze(_f2()) is True",
    "",
    "    def test_cannot_analyze_syntax_error(self):",
    "        assert self.a.can_analyze(_f1()) is False",
    "",
    "    def test_cannot_analyze_test_failure(self):",
    "        assert self.a.can_analyze(_f3()) is False",
    "",
    "    def test_returns_rca_report(self):",
    "        assert isinstance(self.a.analyze(_f2()), RCAReport)",
    "",
    "    def test_causal_category(self):",
    "        assert self.a.analyze(_f2()).causal_category == CAUSAL_DEPENDENCY",
    "",
    "    def test_failure_class_preserved(self):",
    "        assert self.a.analyze(_f2()).failure_class == 'dependency_error'",
    "",
    "    def test_high_confidence_with_package(self):",
    "        assert self.a.analyze(_f2(failing_package='somepkg==1.0')).rca_confidence == 1.0",
    "",
    "    def test_medium_confidence_no_package(self):",
    "        assert self.a.analyze(_f2(failing_package=None)).rca_confidence == 0.7",
    "",
    "    def test_missing_dep_summary(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_missing_dependency'))",
    "        assert 'resolution failed' in r.summary.lower() or 'pip' in r.summary.lower()",
    "",
    "    def test_invalid_req_summary(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_invalid_requirement'))",
    "        assert 'invalid' in r.summary.lower() or 'syntax' in r.summary.lower()",
    "",
    "    def test_build_fail_summary(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_build_failure'))",
    "        assert 'build' in r.summary.lower()",
    "",
    "    def test_package_in_observed_evidence(self):",
    "        r = self.a.analyze(_f2(failing_package='mylib==0.9'))",
    "        assert r.observed_evidence['failing_package'] == 'mylib==0.9'",
    "",
    "    def test_python_version_in_evidence(self):",
    "        r = self.a.analyze(_f2(python_version='3.11.4'))",
    "        assert r.observed_evidence['python_version'] == '3.11.4'",
    "",
    "    def test_pip_commands_in_evidence(self):",
    "        r = self.a.analyze(_f2(pip_commands=['pip install -r requirements.txt']))",
    "        assert r.observed_evidence['pip_commands'] == ['pip install -r requirements.txt']",
    "",
    "    def test_investigation_for_missing(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_missing_dependency', failing_package='somelib==3.0'))",
    "        assert any('PyPI' in s or 'pip index' in s for s in r.suggested_investigation)",
    "",
    "    def test_investigation_for_invalid_req(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_invalid_requirement'))",
    "        assert any('requirements.txt' in s for s in r.suggested_investigation)",
    "",
    "    def test_investigation_for_build_failure(self):",
    "        r = self.a.analyze(_f2(failure_subcategory='pip_build_failure'))",
    "        assert any('compiler' in s.lower() or 'build' in s.lower() for s in r.suggested_investigation)",
    "",
    "    def test_limitations_populated(self):",
    "        assert len(self.a.analyze(_f2()).limitations) >= 1",
    "",
    "",
    "# ===========================================================================",
    "# TestFailureAnalyzer",
    "# ===========================================================================",
    "",
    "class TestTestFailureAnalyzer:",
    "    def setup_method(self):",
    "        self.a = TestFailureAnalyzer()",
    "",
    "    def test_can_analyze(self):",
    "        assert self.a.can_analyze(_f3()) is True",
    "",
    "    def test_cannot_analyze_syntax_error(self):",
    "        assert self.a.can_analyze(_f1()) is False",
    "",
    "    def test_cannot_analyze_dependency_error(self):",
    "        assert self.a.can_analyze(_f2()) is False",
    "",
    "    def test_returns_rca_report(self):",
    "        assert isinstance(self.a.analyze(_f3()), RCAReport)",
    "",
    "    def test_causal_category(self):",
    "        assert self.a.analyze(_f3()).causal_category == CAUSAL_TEST",
    "",
    "    def test_failure_class_is_test_failure(self):",
    "        assert self.a.analyze(_f3()).failure_class == 'test_failure'",
    "",
    "    def test_python_exception_inside_test_stays_test_failure(self):",
    "        # A Python exception within pytest must NOT reclassify to runtime_error.",
    "        r = self.a.analyze(_f3(test_error_type='ValueError', error_message='bad value'))",
    "        assert r.failure_class == 'test_failure'",
    "        assert r.causal_category == CAUSAL_TEST",
    "",
    "    def test_python_exception_stored_in_subcategory(self):",
    "        # Exception type stored in failure_subcategory, not escalated to runtime_error.",
    "        r = self.a.analyze(_f3(test_error_type='ZeroDivisionError'))",
    "        assert r.failure_subcategory == 'ZeroDivisionError'",
    "",
    "    def test_high_confidence_with_test_ids(self):",
    "        assert self.a.analyze(_f3()).rca_confidence == 1.0",
    "",
    "    def test_medium_confidence_without_test_ids(self):",
    "        assert self.a.analyze(_f3(failed_test_ids=[])).rca_confidence == 0.8",
    "",
    "    def test_test_counts_in_evidence(self):",
    "        r = self.a.analyze(_f3(tests_failed=3, tests_passed=17))",
    "        assert r.observed_evidence['tests_failed'] == 3",
    "        assert r.observed_evidence['tests_passed'] == 17",
    "",
    "    def test_test_ids_in_evidence(self):",
    "        r = self.a.analyze(_f3(failed_test_ids=['tests/test_math.py::test_add']))",
    "        assert 'tests/test_math.py::test_add' in r.observed_evidence['failed_test_ids']",
    "",
    "    def test_summary_contains_test_id(self):",
    "        r = self.a.analyze(_f3(failed_test_ids=['tests/test_math.py::test_div']))",
    "        assert 'tests/test_math.py::test_div' in r.summary",
    "",
    "    def test_summary_contains_error_type(self):",
    "        assert 'AssertionError' in self.a.analyze(_f3()).summary",
    "",
    "    def test_local_cmd_uses_test_id(self):",
    "        r = self.a.analyze(_f3(failed_test_ids=['tests/test_math.py::test_add']))",
    "        assert 'tests/test_math.py::test_add' in r.local_reproduction_command",
    "",
    "    def test_investigation_includes_verbose_pytest(self):",
    "        r = self.a.analyze(_f3())",
    "        assert any('pytest' in s and '-vv' in s for s in r.suggested_investigation)",
    "",
    "    def test_limitations_no_regression_claim(self):",
    "        # F3 must not state the failure is a localized regression.",
    "        r = self.a.analyze(_f3())",
    "        for lim in r.limitations:",
    "            assert 'localized regression' not in lim.lower()",
    "            assert 'environment is functional' not in lim.lower()",
    "",
    "    def test_likely_cause_acknowledges_alternatives(self):",
    "        # F3 likely cause must acknowledge alternative explanations.",
    "        text = self.a.analyze(_f3()).likely_cause.lower()",
    "        assert any(p in text for p in [",
    "            'cannot be excluded', 'cannot exclude', 'alternative causes', 'cannot be ruled out'",
    "        ])",
    "",
    "    def test_limitations_populated(self):",
    "        assert len(self.a.analyze(_f3()).limitations) >= 1",
    "",
    "",
    "# ===========================================================================",
    "# TimeoutAnalyzer",
    "# ===========================================================================",
    "",
    "class TestTimeoutAnalyzer:",
    "    def setup_method(self):",
    "        self.a = TimeoutAnalyzer()",
    "",
    "    def test_can_analyze(self):",
    "        assert self.a.can_analyze(_f4()) is True",
    "",
    "    def test_cannot_analyze_syntax_error(self):",
    "        assert self.a.can_analyze(_f1()) is False",
    "",
    "    def test_cannot_analyze_test_failure(self):",
    "        assert self.a.can_analyze(_f3()) is False",
    "",
    "    def test_returns_rca_report(self):",
    "        assert isinstance(self.a.analyze(_f4()), RCAReport)",
    "",
    "    def test_causal_category(self):",
    "        assert self.a.analyze(_f4()).causal_category == CAUSAL_TIMEOUT",
    "",
    "    def test_failure_class_is_timeout(self):",
    "        assert self.a.analyze(_f4()).failure_class == 'timeout'",
    "",
    "    def test_high_confidence_with_duration_and_orphan(self):",
    "        r = self.a.analyze(_f4(timeout_duration_min=6.0, orphan_process='python run.py'))",
    "        assert r.rca_confidence == 1.0",
    "",
    "    def test_medium_confidence_without_orphan(self):",
    "        assert self.a.analyze(_f4(orphan_process=None)).rca_confidence == 0.8",
    "",
    "    def test_medium_confidence_without_duration(self):",
    "        assert self.a.analyze(_f4(timeout_duration_min=None)).rca_confidence == 0.8",
    "",
    "    def test_duration_in_evidence(self):",
    "        r = self.a.analyze(_f4(timeout_duration_min=6.0))",
    "        assert r.observed_evidence['timeout_duration_min'] == 6.0",
    "",
    "    def test_orphan_in_evidence(self):",
    "        r = self.a.analyze(_f4(orphan_process='python run.py'))",
    "        assert r.observed_evidence['orphan_process'] == 'python run.py'",
    "",
    "    def test_summary_contains_step_name(self):",
    "        assert 'Run Tests' in self.a.analyze(_f4(failed_step='Run Tests')).summary",
    "",
    "    def test_summary_contains_duration(self):",
    "        assert '6' in self.a.analyze(_f4(timeout_duration_min=6.0)).summary",
    "",
    "    def test_likely_cause_no_infinite_loop_claim(self):",
    "        # F4 must not assert infinite loop without log evidence.",
    "        assert 'infinite loop' not in self.a.analyze(_f4()).likely_cause.lower()",
    "",
    "    def test_likely_cause_no_deadlock_claim(self):",
    "        assert 'deadlock' not in self.a.analyze(_f4()).likely_cause.lower()",
    "",
    "    def test_likely_cause_no_network_problem_claim(self):",
    "        assert 'network problem' not in self.a.analyze(_f4()).likely_cause.lower()",
    "",
    "    def test_limitations_mention_blocking_context(self):",
    "        combined = ' '.join(self.a.analyze(_f4()).limitations).lower()",
    "        assert 'thread' in combined or 'blocking' in combined or 'stack' in combined",
    "",
    "    def test_limitations_call_unverified_causes_hypotheses(self):",
    "        combined = ' '.join(self.a.analyze(_f4()).limitations).lower()",
    "        assert 'hypothes' in combined or 'cannot be determined' in combined or 'verified' in combined",
    "",
    "    def test_investigation_suggests_local_timing(self):",
    "        r = self.a.analyze(_f4())",
    "        assert any('durations' in s.lower() or 'locally' in s.lower() for s in r.suggested_investigation)",
    "",
    "",
    "# ===========================================================================",
    "# FallbackAnalyzer",
    "# ===========================================================================",
    "",
    "class TestFallbackAnalyzer:",
    "    def setup_method(self):",
    "        self.a = FallbackAnalyzer()",
    "",
    "    def test_can_analyze_always_true(self):",
    "        assert self.a.can_analyze({}) is True",
    "        assert self.a.can_analyze({'failure_class': 'totally_unknown'}) is True",
    "",
    "    def test_runtime_error_causal_category(self):",
    "        rec = {",
    "            'failure_class': 'runtime_error', 'error_type': 'RuntimeError',",
    "            'error_message': 'something went wrong',",
    "            'traceback_lines': ['Traceback...', 'RuntimeError: something went wrong'],",
    "            'failed_step': 'Run App', 'log_text': 'some content', 'log_line_count': 5,",
    "        }",
    "        assert self.a.analyze(rec).causal_category == CAUSAL_CODE_DEFECT",
    "",
    "    def test_runtime_error_failure_class_preserved(self):",
    "        rec = {'failure_class': 'runtime_error', 'error_type': 'NameError', 'log_text': 'x', 'log_line_count': 1}",
    "        assert self.a.analyze(rec).failure_class == 'runtime_error'",
    "",
    "    def test_empty_log_causal_category(self):",
    "        rec = {'failure_class': 'unknown', 'log_text': '', 'log_line_count': 0}",
    "        assert self.a.analyze(rec).causal_category == CAUSAL_UNKNOWN",
    "",
    "    def test_empty_log_zero_confidence(self):",
    "        rec = {'failure_class': 'unknown', 'log_text': '', 'log_line_count': 0}",
    "        assert self.a.analyze(rec).rca_confidence == 0.0",
    "",
    "    def test_unknown_with_exit_code_low_confidence(self):",
    "        rec = {'failure_class': 'unknown', 'exit_code': 2, 'failed_step': 'Build',",
    "               'log_text': 'some output', 'log_line_count': 10}",
    "        r = self.a.analyze(rec)",
    "        assert r.causal_category == CAUSAL_UNKNOWN",
    "        assert 0.0 < r.rca_confidence <= 0.5",
    "",
    "    def test_unknown_without_context_very_low_confidence(self):",
    "        rec = {'failure_class': 'unknown', 'log_text': 'some content', 'log_line_count': 5}",
    "        assert self.a.analyze(rec).rca_confidence <= 0.4",
    "",
    "    def test_runtime_error_not_test_failure(self):",
    "        # runtime_error must not be classified as CAUSAL_TEST.",
    "        rec = {'failure_class': 'runtime_error', 'error_type': 'ValueError',",
    "               'log_text': 'ValueError: bad', 'log_line_count': 3}",
    "        r = self.a.analyze(rec)",
    "        assert r.failure_class == 'runtime_error'",
    "        assert r.causal_category != CAUSAL_TEST",
    "",
    "    def test_limitations_populated(self):",
    "        rec = {'failure_class': 'unknown', 'log_text': 'some content', 'log_line_count': 3}",
    "        assert len(self.a.analyze(rec).limitations) >= 1",
    "",
    "",
    "# ===========================================================================",
    "# RCAEngine",
    "# ===========================================================================",
    "",
    "class TestRCAEngine:",
    "    def test_default_engine_instance(self):",
    "        assert isinstance(get_default_engine(), RCAEngine)",
    "",
    "    def test_default_engine_has_five_analyzers(self):",
    "        assert len(get_default_engine().analyzers) == 5",
    "",
    "    def test_f1_routed_to_syntax(self):",
    "        r = get_default_engine().analyze_record(_f1())",
    "        assert r.failure_class == 'syntax_error'",
    "        assert r.causal_category == CAUSAL_CODE_DEFECT",
    "",
    "    def test_f2_routed_to_dependency(self):",
    "        r = get_default_engine().analyze_record(_f2())",
    "        assert r.failure_class == 'dependency_error'",
    "        assert r.causal_category == CAUSAL_DEPENDENCY",
    "",
    "    def test_f3_routed_to_test_failure(self):",
    "        r = get_default_engine().analyze_record(_f3())",
    "        assert r.failure_class == 'test_failure'",
    "        assert r.causal_category == CAUSAL_TEST",
    "",
    "    def test_f4_routed_to_timeout(self):",
    "        r = get_default_engine().analyze_record(_f4())",
    "        assert r.failure_class == 'timeout'",
    "        assert r.causal_category == CAUSAL_TIMEOUT",
    "",
    "    def test_unknown_routed_to_fallback(self):",
    "        rec = {'failure_class': 'unknown', 'log_text': 'some output', 'log_line_count': 3}",
    "        assert get_default_engine().analyze_record(rec).causal_category == CAUSAL_UNKNOWN",
    "",
    "    def test_convenience_function(self):",
    "        r = analyze_record(_f1())",
    "        assert isinstance(r, RCAReport)",
    "        assert r.failure_class == 'syntax_error'",
    "",
    "    def test_batch_returns_list(self):",
    "        recs = [_f1(), _f2(), _f3(), _f4()]",
    "        reports = get_default_engine().analyze_batch(recs)",
    "        assert len(reports) == 4",
    "        assert all(isinstance(r, RCAReport) for r in reports)",
    "",
    "    def test_batch_preserves_order(self):",
    "        recs = [_f1(run_id='r1'), _f2(run_id='r2'), _f3(run_id='r3'), _f4(run_id='r4')]",
    "        reports = get_default_engine().analyze_batch(recs)",
    "        assert [r.run_id for r in reports] == ['r1', 'r2', 'r3', 'r4']",
    "",
    "    def test_custom_engine_fallback_catches_unregistered(self):",
    "        engine = RCAEngine(analyzers=[TimeoutAnalyzer(), FallbackAnalyzer()])",
    "        r = engine.analyze_record(_f1())",
    "        assert r is not None",
    "",
    "    def test_empty_engine_safety_fallback(self):",
    "        engine = RCAEngine()",
    "        r = engine.analyze_record(_f1())",
    "        assert isinstance(r, RCAReport)",
    "",
    "    def test_all_report_fields_present(self):",
    "        r = get_default_engine().analyze_record(_f3())",
    "        assert r.summary != ''",
    "        assert r.likely_cause != ''",
    "        assert isinstance(r.suggested_investigation, list)",
    "        assert isinstance(r.limitations, list)",
    "        assert isinstance(r.observed_evidence, dict)",
    "        assert isinstance(r.primary_evidence_lines, list)",
    "",
    "    def test_confidence_in_valid_range(self):",
    "        for rec in [_f1(), _f2(), _f3(), _f4()]:",
    "            r = get_default_engine().analyze_record(rec)",
    "            assert 0.0 <= r.rca_confidence <= 1.0",
    "",
    "",
    "# ===========================================================================",
    "# Edge Cases",
    "# ===========================================================================",
    "",
    "class TestEdgeCases:",
    "    def test_syntax_no_file_or_tb(self):",
    "        rec = {'failure_class': 'syntax_error', 'error_type': 'SyntaxError', 'error_message': 'unexpected EOF'}",
    "        r = SyntaxAnalyzer().analyze(rec)",
    "        assert isinstance(r, RCAReport)",
    "        assert r.rca_confidence >= 0.0",
    "",
    "    def test_dependency_all_none(self):",
    "        rec = {'failure_class': 'dependency_error'}",
    "        r = DependencyAnalyzer().analyze(rec)",
    "        assert isinstance(r, RCAReport)",
    "        assert r.rca_confidence == 0.7",
    "",
    "    def test_test_failure_no_tests_info(self):",
    "        rec = {'failure_class': 'test_failure', 'test_error_type': 'AssertionError'}",
    "        r = TestFailureAnalyzer().analyze(rec)",
    "        assert isinstance(r, RCAReport)",
    "",
    "    def test_timeout_minimal(self):",
    "        rec = {'failure_class': 'timeout'}",
    "        r = TimeoutAnalyzer().analyze(rec)",
    "        assert isinstance(r, RCAReport)",
    "        assert r.rca_confidence == 0.8",
    "",
    "    def test_fallback_empty_record(self):",
    "        r = FallbackAnalyzer().analyze({})",
    "        assert isinstance(r, RCAReport)",
    "",
    "    def test_dict_record_accepted(self):",
    "        r = get_default_engine().analyze_record(_f1())",
    "        assert r.failure_class == 'syntax_error'",
]

content = "\n".join(LINES) + "\n"
DEST.write_text(content, encoding="utf-8")
print(f"Written {len(content)} chars to {DEST}")
